before:
  hooks:
    - go mod tidy

builds:
  - id: weather_fetcher
    binary: weather_fetcher
    main: ./cmd/weather_fetcher
    goos:
      - linux
    goarch:
      - amd64
  - id: temperature_changer
    binary: temperature_changer
    main: ./cmd/temperature_changer
    goos:
      - linux
    goarch:
      - amd64
  - id: pipes_master
    binary: pipes_master
    main: ./cmd/pipes_master
    goos:
      - linux
    goarch:
      - amd64
  - id: fuel_analyzer
    binary: fuel_analyzer
    main: ./cmd/fuel_analyzer
    goos:
      - linux
    goarch:
      - amd64
  - id: heater
    binary: heater
    main: ./cmd/heater
    goos:
      - linux
    goarch:
      - amd64
  - id: expense-predictor
    binary: expense-predictor
    main: ./cmd/expense_predictor
    goos:
      - linux
    goarch:
      - amd64

kos:
  - id: weather_fetcher
    repository: ghcr.io/moleus/iot-heating-system
    main: ./cmd/weather_fetcher
    tags:
      - '{{.Version}}'
      - latest
    base_import_paths: true
    bare: false
    preserve_import_paths: false
    platforms:
      - "linux/amd64"
  - id: temperature_changer
    repository: ghcr.io/moleus/iot-heating-system
    main: ./cmd/temperature_changer
    tags:
      - '{{.Version}}'
      - latest
    base_import_paths: true
    bare: false
    preserve_import_paths: false
    platforms:
      - "linux/amd64"
  - id: pipes_master
    repository: ghcr.io/moleus/iot-heating-system
    main: ./cmd/pipes_master
    tags:
      - '{{.Version}}'
      - latest
    base_import_paths: true
    bare: false
    preserve_import_paths: false
    platforms:
      - "linux/amd64"
  - id: fuel_analyzer
    repository: ghcr.io/moleus/iot-heating-system
    main: ./cmd/fuel_analyzer
    tags:
      - '{{.Version}}'
      - latest
    base_import_paths: true
    bare: false
    preserve_import_paths: false
    platforms:
      - "linux/amd64"
  - id: heater
    repository: ghcr.io/moleus/iot-heating-system
    main: ./cmd/heater
    tags:
      - '{{.Version}}'
      - latest
    base_import_paths: true
    bare: false
    preserve_import_paths: false
    platforms:
      - "linux/amd64"
  - id: heater
    repository: ghcr.io/moleus/iot-heating-system
    main: ./cmd/expense_predictor
    tags:
      - '{{.Version}}'
      - latest
    base_import_paths: true
    bare: false
    preserve_import_paths: false
    platforms:
      - "linux/amd64"
