version: '3.7'

services:
  weather-fetcher:
    image: ghcr.io/moleus/iot-heating-system/weather_fetcher:latest
    env_file:
      - .env
    networks:
      - iot-heating-system
    ports:
      - "127.0.0.1:8080:8080"

  pipes-master:
    image: ghcr.io/moleus/iot-heating-system/pipes_master:latest
    networks:
      - iot-heating-system

  temperature-changer:
    image: ghcr.io/moleus/iot-heating-system/temperature_changer:latest
    networks:
      - iot-heating-system
    depends_on:
      - mosquitto

  fuel-analyzer:
    image: ghcr.io/moleus/iot-heating-system/fuel_analyzer:latest
    networks:
      - iot-heating-system

  heater:
    image: ghcr.io/moleus/iot-heating-system/heater:latest
    networks:
      - iot-heating-system

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.100.1
    ports:
      - "127.0.0.1:8428:8428"
    networks:
      - iot-heating-system

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    user: "1000:1000"
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - iot-heating-system

  telegraf:
    image: telegraf:1.30.2
    volumes:
      - ./mqtt/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - iot-heating-system

  grafana:
    image: grafana/grafana:10.1.10
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - iot-heating-system

networks:
  iot-heating-system:
