{
 "title": "IoT Heating System",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pipes temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "mqtt_consumer_in_temperature{}", "legendFormat": "In temperature" },
    {
     "expr": "mqtt_consumer_out_temperature{}",
     "legendFormat": "Out temperature"
    }
   ]
  },
  {
   "title": "Pipes pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "кг/с" } },
   "targets": [
    {
     "expr": "mqtt_consumer_value{topic=\"target/pipes/pressure\"}",
     "legendFormat": "Pressure"
    }
   ]
  },
  {
   "title": "Air temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "mqtt_consumer_outside{}", "legendFormat": "Outside" },
    { "expr": "mqtt_consumer_at_home{}", "legendFormat": "At home" }
   ]
  },
  {
   "title": "Fuel expenses",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "тыс.м3/час" } },
   "targets": [
    {
     "expr": "mqtt_consumer_value{topic=\"target/fuel_expenses\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Predictions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mqtt_consumer_temperature{topic=\"predictions/weather\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fuel expenses Predictions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "тыс.м3/час" } },
   "targets": [
    {
     "expr": "mqtt_consumer_consumption{topic=\"predictions/fuel_expenses\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}