###
GET http://127.0.0.1:8080/weather?lat=11.11&lon=11.11&days=2
###
GET http://127.0.0.1:8080/analyze?required_temp=20&outside_temp=-1.3&efficiency=0.92&specific_heat_of_combustion_fuel=33500&design_outside_temp=-24&design_capacity=21.5
