name: Run tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read
  pull-requests: read

env:
  BRANCH_NAME: "${{ github.head_ref || github.ref_name }}"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          args: --rm-dist --skip-validate --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: ko-build/setup-ko@v0.6
      - run: ko build --platform=linux/amd64 --base-import-paths -t devel-${{ env.BRANCH_NAME }}
